// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Falling back to DATABASE_URL keeps `prisma generate` working during a build
// that has no DIRECT_URL, but if that URL is the transaction pooler then
// `prisma migrate` will hang rather than fail — so say so out loud.
if (!process.env["DIRECT_URL"]) {
  console.warn(
    "[prisma.config] DIRECT_URL is not set; falling back to DATABASE_URL. " +
      "If that points at Supabase's transaction pooler (port 6543), " +
      "`prisma migrate` will hang instead of failing. Set DIRECT_URL to the " +
      "same database on port 5432 — see .env.example.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --project prisma/tsconfig.json prisma/seed.ts",
  },
  datasource: {
    // The Prisma CLI (migrate, studio) needs a session-mode connection: Migrate
    // takes a session-level advisory lock, which Supabase's transaction pooler
    // (port 6543) can't hold, so `migrate deploy` hangs forever. DIRECT_URL is
    // the same database via the session pooler (port 5432). The app itself
    // keeps using DATABASE_URL through src/lib/client.ts, which is the right
    // choice for many short-lived web requests.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
