// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --project prisma/tsconfig.json prisma/seed.ts",
  },
  datasource: {
    // The Prisma CLI (migrate, studio) needs a session-mode connection: Migrate
    // takes a session-level advisory lock, which Supabase's transaction pooler
    // (port 6543) can't hold, so `migrate deploy` hangs forever. DIRECT_URL is
    // the same database via the session pooler (port 5432). The app itself
    // keeps using DATABASE_URL through src/lib/client.ts, which is the right
    // choice for many short-lived web requests.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
